name: test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: get dependencies
        run: go get -v -t -d ./...
      - name: run test
        run: go test -v ./lib/...
